#!/bin/sh
set_phonesim_property() {
    /usr/sbin/run-blts-root /usr/bin/dbus-send --system --print-reply \
        --type=method_call --dest=org.ofono /phonesim org.ofono.Modem.SetProperty \
        string:"$1" variant:boolean:"$2" > /dev/null || exit 1
}

if [ "$1" = "1" ]; then
    echo "Enabling the phonesim modem"
    /bin/sleep 2
    set_phonesim_property Powered true
    set_phonesim_property Online true
fi

if [ "$1" = "0" ]; then
    echo "Disabling the phonesim modem"
    set_phonesim_property Online false
    set_phonesim_property Powered false
fi

