# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       phonesim

# >> macros
# << macros

Summary:    Phone simulator.
Version:    0.0.0
Release:    1
Group:      Applications/System
License:    LGPL v2.1
URL:        http://github.com/nemomobile/phonesim
Source0:    %{name}-%{version}.tar.bz2
Source100:  phonesim.yaml
BuildRequires:  pkgconfig(Qt5Gui)

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/phonesim
%{_datadir}/phonesim/default.xml
# >> files
# << files
